# Generated by Django 4.2.5 on 2023-09-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_consumer_email_alter_consumer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='username',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
