# Generated by Django 4.2.5 on 2023-09-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_consumer_email_alter_consumer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='username',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email-Id'),
        ),
    ]
