# Generated by Django 4.2.5 on 2023-09-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_consumer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='fname',
            field=models.CharField(max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='lname',
            field=models.CharField(max_length=30, verbose_name='Last Name'),
        ),
    ]
