# Generated by Django 4.2.5 on 2023-09-26 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
