# Generated by Django 4.2.5 on 2023-09-26 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_rename_customer_shippingaddress_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
