# Generated by Django 4.2.5 on 2023-09-26 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consumer',
        ),
    ]
