# Generated by Django 4.2.5 on 2023-09-28 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_product_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
