# Generated by Django 4.2.5 on 2023-09-30 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_rename_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='name',
        ),
    ]
