# Generated by Django 4.2.5 on 2023-10-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_amount',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
